CREATE TABLE CLIENTE (
    Id int NOT NULL PRIMARY KEY,
    CodIdentificadorTotvs int NOT NULL,
	Cpf nvarchar(50) NOT NULL,
    PROGRAMA_DESCONTO_ID int FOREIGN KEY REFERENCES PROGRAMA_DESCONTO(ID)
);